version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  reviewers:
  - hakbailey
  ignore:
  - dependency-name: django-compressor
    versions:
    - 2.4.1
  - dependency-name: django-debug-toolbar
    versions:
    - 3.2.1
  - dependency-name: pytest-django
    versions:
    - 4.2.0
  - dependency-name: django
    versions:
    - 3.1.6
    - 3.1.7
    - "3.2"
  - dependency-name: python-dotenv
    versions:
    - 0.16.0
    - 0.17.0
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
    - 8.2.0
  - dependency-name: gunicorn
    versions:
    - 20.1.0
  - dependency-name: django-crispy-forms
    versions:
    - 1.11.0
    - 1.11.1
    - 1.11.2
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.2
    - 0.20.3
    - 1.0.0
  - dependency-name: celery-progress
    versions:
    - 0.1.0
  - dependency-name: coveralls
    versions:
    - 3.0.1
  - dependency-name: newrelic
    versions:
    - 6.2.0.156
  - dependency-name: cryptography
    versions:
    - 3.3.2
