language: python
python:
  - "3.6"
install:
  - "pip install pipenv"
  - "pip install coveralls"
  - "pipenv install"
  - "pipenv check"
script:
  coverage run manage.py test
after_success:
  coveralls
services:
  - postgresql
