# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementsapicall',
            name='request_data',
            field=models.TextField(help_text='The xml sent (i.e. the "data" '
                                   'kwarg in the requests.patch() call.'),
        ),
    ]
