# Generated by Django 2.2.7 on 2019-11-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20180308_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElementsAPICall',
        ),
    ]
