# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 18:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0010_auto_20171218_1819"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="liaison",
            managers=[
                ("objects_all", django.db.models.manager.Manager()),
            ],
        ),
    ]
