# Generated by Django 3.0.4 on 2020-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0013_auto_20171218_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="acq_method",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
